(function() {var implementors = {};
implementors["gmsh_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"gmsh_sys/struct.max_align_t.html\" title=\"struct gmsh_sys::max_align_t\">max_align_t</a>",synthetic:false,types:["gmsh_sys::max_align_t"]},];
implementors["rgmsh"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/shapes/struct.Point.html\" title=\"struct rgmsh::model::shapes::Point\">Point</a>",synthetic:false,types:["rgmsh::model::shapes::Point"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/shapes/struct.Torus.html\" title=\"struct rgmsh::model::shapes::Torus\">Torus</a>",synthetic:false,types:["rgmsh::model::shapes::Torus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/struct.PointTag.html\" title=\"struct rgmsh::model::PointTag\">PointTag</a>",synthetic:false,types:["rgmsh::model::PointTag"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/struct.CurveTag.html\" title=\"struct rgmsh::model::CurveTag\">CurveTag</a>",synthetic:false,types:["rgmsh::model::CurveTag"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/struct.WireTag.html\" title=\"struct rgmsh::model::WireTag\">WireTag</a>",synthetic:false,types:["rgmsh::model::WireTag"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/struct.SurfaceTag.html\" title=\"struct rgmsh::model::SurfaceTag\">SurfaceTag</a>",synthetic:false,types:["rgmsh::model::SurfaceTag"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/struct.ShellTag.html\" title=\"struct rgmsh::model::ShellTag\">ShellTag</a>",synthetic:false,types:["rgmsh::model::ShellTag"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rgmsh/model/struct.VolumeTag.html\" title=\"struct rgmsh::model::VolumeTag\">VolumeTag</a>",synthetic:false,types:["rgmsh::model::VolumeTag"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()